### Get all persons
GET http://localhost:3001/api/persons

### Get one person
GET http://localhost:3001/api/persons/68ef6c8231da3b0ba7facaad

### Delete one person CHANGE ID
DELETE http://localhost:3001/api/persons/68ef6c8231da3b0ba7facaad

### Test 400 error
GET http://localhost:3001/api/persons/68ef65

### Test 404 error
GET http://localhost:3001/api/persons/68ef6576d4622a62c3266f19


### Create a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Viivi Alitalo",
  "number": "045-2889933"
}

### Put
PUT http://localhost:3001/api/persons/68ef6eb4f6c7632cd8d713b4
Content-Type: application/json

{
  "name": "Viivi Alitalo",
  "number": "123-456-789"
}

### Test 'name or number missing' error
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Viivi Alitalo",
  "number": ""
}

### Test 'name must be unique' error
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mary Poppendieck",
  "number": "0452889933"
}

